#!/bin/sh

sudo adduser --no-create-home --home /opt/registration --system --group registration

systemctl enable registration
systemctl enable registration-training

# If config files don't exist, copy them in. This is so any customizations aren't overwritten
# when the package is upgraded
if [ ! -f /opt/registration/registration.properties ]; then
    cp /opt/registration/configuration/default.properties /opt/registration/registration.properties
fi

if [ ! -f /opt/registration/registration-training.properties ]; then
    cp /opt/registration/configuration/default-training.properties /opt/registration/registration-training.properties
fi

# Create service data directory if it doesn't exist. Must be writable by the service (subdirectories will be created
# automatically
if [ ! -d /opt/registration/data/ ]; then
    mkdir /opt/registration/data/
    mkdir /opt/registration/data/badgeImage/
    mkdir /opt/registration/data/badgeResource/
    mkdir /opt/registration/data/guestImport/
    mkdir /opt/registration/data/guestImportDLQ/
    mkdir /opt/registration/data/staffImport/
    mkdir /opt/registration/data/staffImportDLQ/
    mkdir /opt/registration/data/staffUpload/
    chown registration /opt/registration/data/ -R
    chgrp registration /opt/registration/data/ -R
    chmod 775 /opt/registration/data/ -R
fi